In [62]:
import tensorflow as tf
tf.__version__

'2.9.0'

In [63]:
#Creating tensors using tf.constant
scalar = tf.constant(8)
print(scalar)

tf.Tensor(8, shape=(), dtype=int32)


In [64]:
scalar.ndim

0

In [65]:
vector = tf.constant([8,8])
print(vector)

tf.Tensor([8 8], shape=(2,), dtype=int32)


In [66]:
vector.ndim

1

In [67]:
matrix = tf.constant([[10,10,10],[7,7,7],[9,9,9]])
print(matrix)
matrix.ndim

tf.Tensor(
[[10 10 10]
 [ 7  7  7]
 [ 9  9  9]], shape=(3, 3), dtype=int32)


2

In [68]:
#default will give 32 bit numbers
matrix_new = tf.constant([[10.0,10.0],[7.0,7.0]],dtype=tf.float16)
print(matrix_new)

tf.Tensor(
[[10. 10.]
 [ 7.  7.]], shape=(2, 2), dtype=float16)


In [69]:
tensor = tf.constant([[[10,10],[7,7]],
                     [[8,8],[9,9]]])
print(tensor)
tensor.ndim

tf.Tensor(
[[[10 10]
  [ 7  7]]

 [[ 8  8]
  [ 9  9]]], shape=(2, 2, 2), dtype=int32)


3

In [70]:
#Creating tensors using tf.variable
variable_tensor = tf.Variable([10,10])
constant_tensor = tf.constant([8,8])
print(variable_tensor)
print(constant_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>
tf.Tensor([8 8], shape=(2,), dtype=int32)


In [71]:
variable_tensor[0].assign(7)
print(variable_tensor)

#WILL NOT WORK
# constant_tensor[0].assign(7) = Gives an attribute error

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 10], dtype=int32)>


In [72]:
#Creating random Tensors
random_1 = tf.random.Generator.from_seed(40)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.78953624,  0.53897345],
       [-0.48535708,  0.74055266],
       [ 0.31662667, -1.4391748 ]], dtype=float32)>

In [73]:
#SHUFFLING THE ORDER OF ELEMENTS IN A TENSOR
not_shuffled = tf.constant([[10,10],[7,7],[8,8]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 10],
       [ 7,  7],
       [ 8,  8]], dtype=int32)>

In [74]:
#Both work
#shuffled = tf.random.shuffle(not_shuffled,seed=30)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 10],
       [ 7,  7],
       [ 8,  8]], dtype=int32)>

In [75]:
#TURNING NUMPY ARRAYS INTO TENSORS
#tensors can be run on a gpu much faster

import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
print("Numpy Array = ",numpy_A)

#converting np array into tensor
A = tf.constant(numpy_A,shape=(3,4,2))
A

Numpy Array =  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


<tf.Tensor: shape=(3, 4, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]], dtype=int32)>

In [78]:
#Tensor Operations Basic
tensor = tf.constant([[10,7],[3,4]])
tensor+10,tensor*2,tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 14],
        [ 6,  8]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>)

In [81]:
#This is faster than regular operators
tf.multiply(tensor,10),tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>)

In [82]:
#Matrix Multiplication
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [100]:
tensor2 = tf.constant([1,2,3,4])
#Reshaping the tensor
tensor2 = tf.reshape(tensor2,shape=(2,2))
tf.matmul(tensor2,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[16, 15],
       [42, 37]], dtype=int32)>

In [111]:
#Using tf.tensordot()
tf.tensordot(tensor,tensor,1) , tf.tensordot(tensor,tensor,0)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
 array([[[[100,  70],
          [ 30,  40]],
 
         [[ 70,  49],
          [ 21,  28]]],
 
 
        [[[ 30,  21],
          [  9,  12]],
 
         [[ 40,  28],
          [ 12,  16]]]], dtype=int32)>)