In [62]:
import tensorflow as tf
tf.__version__

'2.9.0'

In [63]:
#Creating tensors using tf.constant
scalar = tf.constant(8)
print(scalar)

tf.Tensor(8, shape=(), dtype=int32)


In [64]:
scalar.ndim

0

In [65]:
vector = tf.constant([8,8])
print(vector)

tf.Tensor([8 8], shape=(2,), dtype=int32)


In [66]:
vector.ndim

1

In [67]:
matrix = tf.constant([[10,10,10],[7,7,7],[9,9,9]])
print(matrix)
matrix.ndim

tf.Tensor(
[[10 10 10]
 [ 7  7  7]
 [ 9  9  9]], shape=(3, 3), dtype=int32)


2

In [68]:
#default will give 32 bit numbers
matrix_new = tf.constant([[10.0,10.0],[7.0,7.0]],dtype=tf.float16)
print(matrix_new)

tf.Tensor(
[[10. 10.]
 [ 7.  7.]], shape=(2, 2), dtype=float16)


In [69]:
tensor = tf.constant([[[10,10],[7,7]],
                     [[8,8],[9,9]]])
print(tensor)
tensor.ndim

tf.Tensor(
[[[10 10]
  [ 7  7]]

 [[ 8  8]
  [ 9  9]]], shape=(2, 2, 2), dtype=int32)


3

In [70]:
#Creating tensors using tf.variable
variable_tensor = tf.Variable([10,10])
constant_tensor = tf.constant([8,8])
print(variable_tensor)
print(constant_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>
tf.Tensor([8 8], shape=(2,), dtype=int32)


In [71]:
variable_tensor[0].assign(7)
print(variable_tensor)

#WILL NOT WORK
# constant_tensor[0].assign(7) = Gives an attribute error

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 10], dtype=int32)>


In [72]:
#Creating random Tensors
random_1 = tf.random.Generator.from_seed(40)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.78953624,  0.53897345],
       [-0.48535708,  0.74055266],
       [ 0.31662667, -1.4391748 ]], dtype=float32)>

In [73]:
#SHUFFLING THE ORDER OF ELEMENTS IN A TENSOR
not_shuffled = tf.constant([[10,10],[7,7],[8,8]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 10],
       [ 7,  7],
       [ 8,  8]], dtype=int32)>

In [74]:
#Both work
#shuffled = tf.random.shuffle(not_shuffled,seed=30)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 10],
       [ 7,  7],
       [ 8,  8]], dtype=int32)>

In [75]:
#TURNING NUMPY ARRAYS INTO TENSORS
#tensors can be run on a gpu much faster

import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
print("Numpy Array = ",numpy_A)

#converting np array into tensor
A = tf.constant(numpy_A,shape=(3,4,2))
A

Numpy Array =  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


<tf.Tensor: shape=(3, 4, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]], dtype=int32)>

In [78]:
#Tensor Operations Basic
tensor = tf.constant([[10,7],[3,4]])
tensor+10,tensor*2,tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 14],
        [ 6,  8]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>)

In [81]:
#This is faster than regular operators
tf.multiply(tensor,10),tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>)

In [82]:
#Matrix Multiplication
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [100]:
tensor2 = tf.constant([1,2,3,4])
#Reshaping the tensor
tensor2 = tf.reshape(tensor2,shape=(2,2))
tf.matmul(tensor2,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[16, 15],
       [42, 37]], dtype=int32)>

In [111]:
#Using tf.tensordot()
#axes variable has to sepcified (=1)
tf.tensordot(tensor,tensor,1) , tf.tensordot(tensor,tensor,0)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
 array([[[[100,  70],
          [ 30,  40]],
 
         [[ 70,  49],
          [ 21,  28]]],
 
 
        [[[ 30,  21],
          [  9,  12]],
 
         [[ 40,  28],
          [ 12,  16]]]], dtype=int32)>)

In [123]:
#Changing datatype of tensors
tensor3 = tf.cast(tensor,dtype=tf.float32)
print("tensor3 =",tensor3)
#Code runs faster if it has 16 bit precision
tensor_new = tf.cast(tensor,dtype=tf.int16)
tensor_new

tensor3 = tf.Tensor(
[[10.  7.]
 [ 3.  4.]], shape=(2, 2), dtype=float32)


(<tf.Tensor: shape=(2, 2), dtype=int16, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int16)>,
 tf.int32)

In [159]:
#AGGREGATING TENSORS
#Condensing multiple values into smaller values

#1) Getting the absolute values(not really the best)
C = tf.constant([-10,7])
tf.abs(C) #Returns the absolute value

D = tf.constant(np.random.randint(0,100,size=50))
#2) Getting the min and max
print("min = ",tf.reduce_min(D).numpy())
print("max = ",tf.reduce_max(D).numpy())

#3) Getting the mean
print("mean = ",tf.reduce_mean(D).numpy())

#4) Getting the sum
print("sum = ",tf.reduce_sum(D).numpy())

#5) Getting the variance and standard deviation
D = tf.cast(D,dtype=tf.float32)
D.dtype
print("Variance = ",tf.math.reduce_variance(D).numpy())
print("Standard Deviation = ",tf.math.reduce_std(D).numpy())

min =  0
max =  98
mean =  52
sum =  2600
Variance =  817.8
Standard Deviation =  28.597202


In [175]:
#Finding positional minimum and maximum
tf.random.set_seed(42)
E = tf.random.uniform(shape=[50])
tf.argmax(E) , E[tf.argmax(E)]
#For minimum use argmin()

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>)

In [185]:
#Squeezing Tensors : Removing all single dimesions
tf.random.set_seed(42)
F = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,50))
print(F)
print("shape =",F.shape)
F_squeezed = tf.squeeze(F)
F_squeezed.shape , F_squeezed

tf.Tensor(
[[[[0.6645621  0.44100678 0.3528825  0.46448255 0.03366041 0.68467236
    0.74011743 0.8724445  0.22632635 0.22319686 0.3103881  0.7223358
    0.13318717 0.5480639  0.5746088  0.8996835  0.00946367 0.5212307
    0.6345445  0.1993283  0.72942245 0.54583454 0.10756552 0.6767061
    0.6602763  0.33695042 0.60141766 0.21062577 0.8527372  0.44062173
    0.9485276  0.23752594 0.81179297 0.5263394  0.494308   0.21612847
    0.8457197  0.8718841  0.3083862  0.6868038  0.23764038 0.7817228
    0.9671384  0.06870162 0.79873943 0.66028714 0.5871513  0.16461694
    0.7381023  0.32054043]]]], shape=(1, 1, 1, 50), dtype=float32)
shape = (1, 1, 1, 50)


(TensorShape([50]),
 <tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>)

In [189]:
#One-Hot encoding tensors
l = [0, 1, 2, 3] #Created list
tf.one_hot(l,depth=4) #depth should be equal to number of elements

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [196]:
#Custom values for one-hot encoding (Rarely used)
Z = tf.one_hot(l,depth=4,on_value="yes",off_value="no")
Z

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yes', b'no', b'no', b'no'],
       [b'no', b'yes', b'no', b'no'],
       [b'no', b'no', b'yes', b'no'],
       [b'no', b'no', b'no', b'yes']], dtype=object)>